In [1]:
import numpy as np
import cv2
import json
from matplotlib import pyplot as plt
import os
import tensorflow as tf
from tensorflow.keras.layers import AveragePooling2D
from tensorflow.keras.layers import Dense, Flatten, Conv2D
from tensorflow.keras import Model
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input
from tensorflow.keras.preprocessing.image import img_to_array
from tensorflow.keras.preprocessing.image import load_img
from tensorflow.keras.utils import to_categorical
from sklearn.preprocessing import LabelBinarizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from tensorflow.keras import datasets, layers, models
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import csv
from keras.layers import Dropout ,BatchNormalization
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.layers import Input
from tensorflow.keras.optimizers import Adam
from tensorflow import keras

In [2]:
def read_this(image_file, gray_scale=False):
    image_src = cv2.imread(image_file)
    if gray_scale:
        image_src = cv2.cvtColor(image_src, cv2.COLOR_BGR2GRAY)
    else:
        image_src = cv2.cvtColor(image_src, cv2.COLOR_BGR2RGB)
    return image_src

In [3]:
def equalize_this(image_file, gray_scale=False):
    image_src = read_this(image_file=image_file, gray_scale=gray_scale)
    if not gray_scale:
        r_image, g_image, b_image = cv2.split(image_src)

        r_image_eq = cv2.equalizeHist(r_image)
        g_image_eq = cv2.equalizeHist(g_image)
        b_image_eq = cv2.equalizeHist(b_image)

        image_eq = cv2.merge((r_image_eq, g_image_eq, b_image_eq))
        cmap_val = None
    else:
        image_eq = cv2.equalizeHist(image_src)
        cmap_val = 'gray'
        status
    return image_eq


In [5]:

a=equalize_this(image_file='untitled.png')
cv2.imwrite('unknown1.png',a)

True

In [7]:
DIRECTORY = r"check\\"
closeim = cv2.imread('unknown1.png')
closingImage = cv2.imread('unknown1.png', cv2.IMREAD_GRAYSCALE)
inputCopy = closingImage.copy()
cnts= cv2.findContours(inputCopy, cv2.RETR_CCOMP, cv2.CHAIN_APPROX_SIMPLE)
cnts = cnts[0] if len(cnts) == 2 else cents[1]
cnts = sorted(cnts,key=lambda x: cv2.boundingRect(x)[0])
i = 10
for c in cnts:
     i = i + 1
     x, y, w, h = cv2.boundingRect(c)
     if h>30 and w>50 and h<200:
        roi = closeim[y:y+h, x:x+w]
        path = os.path.join(DIRECTORY, str(i) + '.png')   
        cv2.imwrite(path,roi)    
        cv2.rectangle(inputCopy,(x,y),(x+w,y+h),(0,255,255),2)   
cv2.imwrite('unknown4.png',inputCopy)    

True

In [9]:
with open('english.csv', mode='r', newline='', encoding='utf-8') as f:
    reader = csv.reader(f)
    gt = {rows[0]:rows[1] for rows in reader}
    gt
path = 'img/'
images = [] 
target = [] 
for root, dirs, files in os.walk(path):
    for file in files:
        with open(os.path.join(root, file), "r") as auto: 
            im = load_img(root+'\\'+file, target_size=(224,224)) 
            im = img_to_array(im)
            im = preprocess_input(im)
            images.append(im)
            target.append(gt['Img/'+file])  

In [11]:
target

['3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '6',
 '6'

In [12]:
images = tf.image.rgb_to_grayscale(
    images, name=None
)

data = np.array(images)
for i in range(0,len(target)):
     target[i]=int(target[i])
targets=np.array(target)  

In [75]:
(trainX, testX, trainY, testY) = train_test_split(data, targets,test_size=0.2)    

numpy.int32

In [102]:
model = models.Sequential()
model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(224,224,1)))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))
model.add(Flatten())
model.add(layers.Dense(1024, activation='relu'))
model.add(Dropout(0.5))
model.add(layers.Dense(512, activation='relu'))
model.add(Dropout(0.5))
model.add(layers.Dense(26,activation='softmax'))
model.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_24 (Conv2D)          (None, 222, 222, 32)      320       
                                                                 
 max_pooling2d_24 (MaxPoolin  (None, 111, 111, 32)     0         
 g2D)                                                            
                                                                 
 conv2d_25 (Conv2D)          (None, 109, 109, 64)      18496     
                                                                 
 max_pooling2d_25 (MaxPoolin  (None, 54, 54, 64)       0         
 g2D)                                                            
                                                                 
 conv2d_26 (Conv2D)          (None, 52, 52, 64)        36928     
                                                                 
 max_pooling2d_26 (MaxPoolin  (None, 26, 26, 64)      

In [103]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['SparseCategoricalAccuracy'])

aug = ImageDataGenerator(
	rotation_range=20,
	zoom_range=0.15,
	width_shift_range=0.2,
	height_shift_range=0.2,
	horizontal_flip=True,
	fill_mode="nearest")

In [202]:

history = model.fit(aug.flow(trainX, trainY, batch_size=32), epochs=40, steps_per_epoch=len(trainX) // 32,validation_steps=len(testX) // 32,
                    validation_data=(testX, testY))






Epoch 1/40
67/67 [==============================] - 56s 840ms/step - loss: 0.4323 - sparse_categorical_accuracy: 0.8613 - val_loss: 0.3483 - val_sparse_categorical_accuracy: 0.8909
Epoch 2/40
67/67 [==============================] - 58s 863ms/step - loss: 0.5345 - sparse_categorical_accuracy: 0.8230 - val_loss: 0.4303 - val_sparse_categorical_accuracy: 0.8685
Epoch 3/40
67/67 [==============================] - 58s 872ms/step - loss: 0.5184 - sparse_categorical_accuracy: 0.8363 - val_loss: 0.3808 - val_sparse_categorical_accuracy: 0.8965
Epoch 4/40
67/67 [==============================] - 59s 880ms/step - loss: 0.5236 - sparse_categorical_accuracy: 0.8306 - val_loss: 0.3269 - val_sparse_categorical_accuracy: 0.9049
Epoch 5/40
67/67 [==============================] - 59s 885ms/step - loss: 0.4640 - sparse_categorical_accuracy: 0.8471 - val_loss: 0.3441 - val_sparse_categorical_accuracy: 0.9007
Epoch 6/40
67/67 [==============================] - 60s 888ms/step - loss: 0.4450 - sparse_cate

In [229]:
# preds = model.predict(data2, batch_size=32)
# for i in preds:
#     print  (preds*100)
# np.argmax(preds)    

1/1 [==============================] - 0s 29ms/step
[[2.9081600e-03 5.6318545e-01 2.6296198e-03 9.9225876e+01 9.0150708e-05
  1.6777843e-06 2.0335228e-03 2.0228622e-04 4.8662960e-03 9.6279045e-04
  5.0870608e-06 1.2775450e-03 2.4142668e-07 2.4989941e-03 1.2889704e-01
  1.6928016e-03 1.6508177e-03 4.4175031e-04 5.0139120e-03 2.1715976e-04
  5.4480001e-02 7.5914839e-04 7.9657933e-05 1.3228068e-09 8.6361638e-07
  2.3994426e-04]]


3

True

In [15]:
from PIL import Image, ImageOps


def padding(img, expected_size):
    desired_size = expected_size
    delta_width = desired_size - img.size[0]
    delta_height = desired_size - img.size[1]
    pad_width = delta_width // 2
    pad_height = delta_height // 2
    padding = (pad_width, pad_height, delta_width - pad_width, delta_height - pad_height)
    return ImageOps.expand(img, padding)


def resize_with_padding(img, expected_size):
    img.thumbnail((expected_size[0], expected_size[1]))
    # print(img.size)
    delta_width = expected_size[0] - img.size[0]
    delta_height = expected_size[1] - img.size[1]
    pad_width = delta_width // 2
    pad_height = delta_height // 2
    padding = (pad_width, pad_height, delta_width - pad_width, delta_height - pad_height)
    return ImageOps.expand(img, padding,fill=(255,255,255))




In [173]:

    img = resize_with_padding(close, (224, 224))
    print(img.size)
    img.show()

(224, 224)


In [207]:
model.save("text_detector.model", save_format="h5")

In [4]:
close = load_img('check/22.png')
img = resize_with_padding(close, (224, 224))
close1 = img_to_array(img)
close2= preprocess_input(close1)
close2= tf.image.rgb_to_grayscale(
    close1, name=None
)
datas1=[]
datas1.append(close2)
data2 = np.array(datas1, dtype="float32")
data2.shape
img.show()

In [16]:

data=[]
data4=[]
path = r'check'
for img in os.listdir(path):
        print (img)
        img_path = os.path.join(path, img)
        image = load_img(img_path)
        image = resize_with_padding(image, (224, 224))
        image = img_to_array(image)
        image = preprocess_input(image)
        image= tf.image.rgb_to_grayscale(image, name=None)
        data4.append(image)
        image1 = np.array(data4, dtype="float32")
        print(image1)
        data.append(image1)
        data4.clear
        data4=[]
     

13.png
[[[[0.99990004]
   [0.99990004]
   [0.99990004]
   ...
   [0.99990004]
   [0.99990004]
   [0.99990004]]

  [[0.99990004]
   [0.99990004]
   [0.99990004]
   ...
   [0.99990004]
   [0.99990004]
   [0.99990004]]

  [[0.99990004]
   [0.99990004]
   [0.99990004]
   ...
   [0.99990004]
   [0.99990004]
   [0.99990004]]

  ...

  [[0.99990004]
   [0.99990004]
   [0.99990004]
   ...
   [0.99990004]
   [0.99990004]
   [0.99990004]]

  [[0.99990004]
   [0.99990004]
   [0.99990004]
   ...
   [0.99990004]
   [0.99990004]
   [0.99990004]]

  [[0.99990004]
   [0.99990004]
   [0.99990004]
   ...
   [0.99990004]
   [0.99990004]
   [0.99990004]]]]
14.png
[[[[0.99990004]
   [0.99990004]
   [0.99990004]
   ...
   [0.99990004]
   [0.99990004]
   [0.99990004]]

  [[0.99990004]
   [0.99990004]
   [0.99990004]
   ...
   [0.99990004]
   [0.99990004]
   [0.99990004]]

  [[0.99990004]
   [0.99990004]
   [0.99990004]
   ...
   [0.99990004]
   [0.99990004]
   [0.99990004]]

  ...

  [[0.99990004]
   [0.9999

In [406]:

c=""
for i in range(len(data)):
    preds = model.predict(data[i], batch_size=32)
    b=giveletter(np.argmax(preds)) 
    c = str(b) + c
print(reverse(c))

1/1 [==============================] - 0s 36ms/step
CHARACT


In [335]:
def giveletter(a):
    if(a==0):
        return'A'
    elif(a==1):
        return('B') 
    elif(a==2):
        return('C')
    elif(a==3):
        return('D') 
    elif(a==4):
        return('E') 
    elif(a==5):
        return('F')  
    elif(a==6):
        return('G')
    elif(a==7):
        return'H'
    elif(a==8):
        return('I') 
    elif(a==9):
        return('J')
    elif(a==10):
        return('K') 
    elif(a==11):
        return('L')
    elif(a==12):
        return('M')
    elif(a==13):
        return('N')
    elif(a==14):
        return('O')
    elif(a==15): 
        return('P')
    elif(a==16): 
        return('Q')
    elif(a==17): 
        return('R')
    elif(a==18): 
        return('S')
    elif(a==19): 
        return('T') 
    elif(a==20): 
        return('U')
    elif(a==21): 
        return('V')
    elif(a==22): 
        return('W')  
    elif(a==23): 
        return('X')  
    elif(a==24): 
        return('Y')
    elif(a==25): 
        return('Z')       
        
     
        

In [274]:
data[0].shape

(1, 224, 224, 1)

In [262]:
data2.shape

(1, 224, 224, 1)

In [319]:
a=os.listdir(path)

In [340]:
def reverse(s):
    str = ""
    for i in s:
        str = i + str
    return str